@echo off
REM AI Employee - Monthly Subscription Audit
REM Auto-generated by scheduler skill

echo ================================================
echo AI Employee - Monthly Subscription Audit
echo ================================================
echo Time: %DATE% %TIME%
echo.

cd /d "."

qwen --cwd "AI_Employee_Vault" "Review all transactions this month, identify subscriptions, and flag any unused services for cancellation"

echo.
echo Monthly Subscription Audit complete.
echo ================================================
